server:
  port: 8810
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
spring:
  application:
    name: discovery-eureka
eureka:
  client:
    service-url:
      defaultZone: http://172.19.23.157:${server.port}/eureka
  instance:
      prefer-ip-address: true # 将自己的IP注册到eureka server，如果为false（默认），则注册的是hostname
      hostname: discovery-eureka
      instance-id: ${spring.application.name}:${server.port}
  server:
    enable-self-preservation: false # 关闭自我保护（自我保护就是不注销微服务）
    eviction-interval-timer-in-ms: 60000 # 清理（无效节点）间隔 默认60*1000毫秒

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS